/* eslint-disable no-useless-assignment */
import {CustomMaterialInstance,CustomMaterialResult,SurfaceTarget} from '../types/custom-materials';import {Opening,RoomDimensions} from '../types/project';import {openingMetrics,roomMetrics} from './calculations';
const valid=(n:number,allowZero=false)=>Number.isFinite(n)&&(allowZero?n>=0:n>0);const surfaceName:Record<SurfaceTarget,string>={floor:'Пол',walls:'Стены',ceiling:'Потолок',custom:'Пользовательская площадь'};
export function calculateCustomMaterial(item:CustomMaterialInstance,room:RoomDimensions,openings:Opening[]):CustomMaterialResult{const m=roomMetrics(room),op=openingMetrics(openings,m.walls);const area=(target:SurfaceTarget,custom:number)=>target==='floor'?m.floor:target==='walls'?op.working:target==='ceiling'?m.ceiling:custom;const s=item.settings;let quantity=0,cost=0,requirement='',surface='',waste=0,unitPrice=0,unit='';
if(item.calculationType==='AREA_PACKAGE'){const x=s as import('../types/custom-materials').AreaPackageSettings,v=area(x.surface,x.customArea);if(!valid(v)||!valid(x.coveragePerPackage)||!valid(x.packagePrice,true))throw Error('Проверьте площадь, упаковку и цену');const need=v*(1+x.wastePercent/100);quantity=Math.ceil(need/x.coveragePerPackage);cost=quantity*x.packagePrice;requirement=`${need.toFixed(2)} м²`;surface=surfaceName[x.surface];waste=x.wastePercent;unitPrice=x.packagePrice;unit=x.unitName}
else if(item.calculationType==='LIQUID_COVERAGE'){const x=s as import('../types/custom-materials').LiquidCoverageSettings,v=area(x.surface,x.customArea);if(!valid(v)||!valid(x.consumptionPerSquareMeter)||!valid(x.coats)||!valid(x.containerVolume))throw Error('Проверьте площадь, расход, слои и объём');const need=v*x.consumptionPerSquareMeter*x.coats*(1+x.wastePercent/100);quantity=Math.ceil(need/x.containerVolume);cost=quantity*x.containerPrice;requirement=`${need.toFixed(2)} л`;surface=surfaceName[x.surface];waste=x.wastePercent;unitPrice=x.containerPrice;unit=x.unitName}
else if(item.calculationType==='LINEAR'){const x=s as import('../types/custom-materials').LinearSettings,base=x.base==='perimeter'?m.perimeter:x.base==='workingPerimeter'?Math.max(0,m.perimeter-op.doorWidth):x.customLength;if(!valid(base)||!valid(x.unitLength))throw Error('Проверьте длину');const need=base*(1+x.wastePercent/100);quantity=Math.ceil(need/x.unitLength);cost=quantity*x.unitPrice;requirement=`${need.toFixed(2)} м`;surface=x.base==='custom'?'Пользовательская длина':'Периметр';waste=x.wastePercent;unitPrice=x.unitPrice;unit=x.unitName}
else if(item.calculationType==='PIECE'){const x=s as import('../types/custom-materials').PieceSettings;if(!valid(x.quantity)||!valid(x.piecesPerPackage))throw Error('Проверьте количество');const need=Math.ceil(x.quantity*(1+x.wastePercent/100));quantity=Math.ceil(need/x.piecesPerPackage);cost=quantity*x.packagePrice;requirement=`${need} шт.`;surface='Штучный расчёт';waste=x.wastePercent;unitPrice=x.packagePrice;unit=x.unitName}
else if(item.calculationType==='DRY_MIX'){const x=s as import('../types/custom-materials').DryMixSettings,v=area(x.surface,x.customArea);if(!valid(v)||!valid(x.consumptionKgPerSquareMeter)||!valid(x.baseThickness)||!valid(x.actualThickness)||!valid(x.bagWeight))throw Error('Проверьте площадь, расход, толщину и мешок');const need=v*x.consumptionKgPerSquareMeter*(x.actualThickness/x.baseThickness)*(1+x.wastePercent/100);quantity=Math.ceil(need/x.bagWeight);cost=quantity*x.bagPrice;requirement=`${need.toFixed(2)} кг`;surface=surfaceName[x.surface];waste=x.wastePercent;unitPrice=x.bagPrice;unit=x.unitName}
else{const x=s as import('../types/custom-materials').VolumeSettings;if(!valid(x.length)||!valid(x.width)||!valid(x.thickness)||!valid(x.volumePerUnit))throw Error('Проверьте размеры и объём поставки');const need=x.length*x.width*x.thickness*(1+x.wastePercent/100);quantity=Math.ceil(need/x.volumePerUnit);cost=quantity*x.unitPrice;requirement=`${need.toFixed(3)} м³`;surface='Объём';waste=x.wastePercent;unitPrice=x.unitPrice;unit=x.unitName}if(waste<0||waste>50||!Number.isFinite(cost)||cost<0)throw Error('Запас должен быть от 0 до 50%, цена — неотрицательной');return{id:item.id,name:item.name,calculationType:item.calculationType,surface,quantity,unit,requirement,waste,unitPrice,cost}}
